trigger:
- master

pool:
  name: yoyo

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'youssefkhaled5222/devops'  # Removed spaces around '/'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '**'  # Adjust based on the location of your Dockerfile
