apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-deployment
  labels:
    app: maven
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: static-site
        image: youssefkhaled5222/devops:s1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
